spring.application.name=GNSProject

server.forward-headers-strategy=framework

server.port=8080

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database=default
spring.jpa.properties.hibernate.format_sql=true

spring.mvc.pathmatch.matching-strategy=ANT_PATH_MATCHER

# Swagger
springdoc.swagger-ui.path=/swagger-ui.html

#smtp
brevo.api.key=${BREVO_API_KEY}

# DB Configuration
spring.datasource.url=jdbc:postgresql://gns-db-instance.cdm604eg66vo.us-west-1.rds.amazonaws.com:5432/gns_db
spring.datasource.username=postgres
spring.datasource.password=16z9CgXnFy2274FEP
spring.datasource.driver-class-name= org.postgresql.Driver

#Redis
spring.data.redis.url=redis://default:ghVIkeRK7IiOBeNM8QgUfup8pub8roJ4@redis-17084.c273.us-east-1-2.ec2.cloud.redislabs.com:17084
spring.data.redis.timeout=60000
spring.data.redis.client-type=lettuce
