spring.application.name=GNSProject

server.forward-headers-strategy=framework

server.port=8080

# DB Configuration
# Native DB config of Spring Boot
spring.datasource.url=jdbc:postgresql://gns-db-instance.cdm604eg66vo.us-west-1.rds.amazonaws.com:5432/gns_db
spring.datasource.username=postgres
spring.datasource.password=16z9CgXnFy2274FEP
spring.datasource.driver-class-name= org.postgresql.Driver

spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database=default
spring.jpa.properties.hibernate.format_sql=true

spring.mvc.pathmatch.matching-strategy=ANT_PATH_MATCHER

# Swagger
springdoc.swagger-ui.path=/swagger-ui.html

# Mail Configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=asifkhalifa20@gmail.com
spring.mail.password=qohor knjp pczd hwwr
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

#Redis
spring.data.redis.url=redis://default:ghVIkeRK7IiOBeNM8QgUfup8pub8roJ4@redis-17084.c273.us-east-1-2.ec2.cloud.redislabs.com:17084
spring.data.redis.timeout=60000
spring.data.redis.client-type=lettuce


spring.mail.properties.mail.debug=true
